apiVersion: v1
kind: Pod
metadata:
  name: vnc
spec:
  containers:
  - name: vnc
    image: reg.alta3.com/ubuntu23
    ports:
    - name: novnc-html
      containerPort: 6901
      protocol: TCP
    - name: novnc
      containerPort: 5901
      protocol: TCP

